package com.example.pifinance_back.Entities;

public enum Country {
    AFGHANISTAN("Afghanistan"),
    ALBANIE("Albanie"),
    ALGERIE("Algérie"),
    ANDORRE("Andorre"),
    ANGOLA("Angola"),
    ANTIGUA_ET_BARBUDA("Antigua-et-Barbuda"),
    ARABIE_SAOUDITE("Arabie saoudite"),
    ARGENTINE("Argentine"),
    ARMENIE("Arménie"),
    AUSTRALIE("Australie"),
    AUTRICHE("Autriche"),
    AZERBAIDJAN("Azerbaïdjan"),
    BAHAMAS("Bahamas"),
    BAHREIN("Bahreïn"),
    BANGLADESH("Bangladesh"),
    BARBADE("Barbade"),
    BELGIQUE("Belgique"),
    BELIZE("Belize"),
    BENIN("Bénin"),
    BHOUTAN("Bhoutan"),
    BIELORUSSIE("Biélorussie"),
    BOLIVIE("Bolivie"),
    BOSNIE_HERZEGOVINE("Bosnie-Herzégovine"),
    BOTSWANA("Botswana"),
    BRESIL("Brésil"),
    BRUNEI("Brunei"),
    BULGARIE("Bulgarie"),
    BURKINA_FASO("Burkina Faso"),
    BURUNDI("Burundi"),
    CAMBODGE("Cambodge"),
    CAMEROUN("Cameroun"),
    CANADA("Canada"),
    CAP_VERT("Cap-Vert"),
    CHILI("Chili"),
    CHINE("Chine"),
    CHYPRE("Chypre"),
    COLOMBIE("Colombie"),
    COMORES("Comores"),
    CONGO_BRAZZAVILLE("Congo-Brazzaville"),
    CONGO_KINSHASA("Congo-Kinshasa"),
    COREE_DU_NORD("Corée du Nord"),
    COREE_DU_SUD("Corée du Sud"),
    COSTA_RICA("Costa Rica"),
    COTE_D_IVOIRE("Côte d'Ivoire"),
    CROATIE("Croatie"),
    CUBA("Cuba"),
    DANEMARK("Danemark"),
    DJIBOUTI("Djibouti"),
    DOMINIQUE("Dominique"),
    EGYPTE("Égypte"),
    EMIRATS_ARABES_UNIS("Émirats arabes unis"),
    EQUATEUR("Équateur"),
    ERYTHREE("Érythrée"),
    ESPAGNE("Espagne"),
    ESTONIE("Estonie"),
    ESWATINI("Eswatini"),
    ETHIOPIE("Éthiopie"),
    FIDJI("Fidji"),
    FINLANDE("Finlande"),
    FRANCE("France"),
    GABON("Gabon"),
    GAMBIE("Gambie"),
    GEORGIE("Géorgie"),
    GHANA("Ghana"),
    GRECE("Grèce"),
    GRENADE("Grenade"),
    GUATEMALA("Guatemala"),
    GUINEE("Guinée"),
    GUINEE_BISSAU("Guinée-Bissau"),
    GUINEE_EQUATORIALE("Guinée équatoriale"),
    GUYANA("Guyana"),
    HAITI("Haïti"),
    HONDURAS("Honduras"),
    HONGRIE("Hongrie"),
    INDE("Inde"),
    INDONESIE("Indonésie"),
    IRAQ("Irak"),
    IRAN("Iran"),
    IRLANDE("Irlande"),
    ISLANDE("Islande"),
    ITALIE("Italie"),
    JAMAIQUE("Jamaïque"),
    JAPON("Japon"),
    JORDANIE("Jordanie"),
    KAZAKHSTAN("Kazakhstan"),
    KENYA("Kenya"),
    KIRGHIZISTAN("Kirghizistan"),
    KIRIBATI("Kiribati"),
    KOWEIT("Koweït"),
    LAOS("Laos"),
    LESOTHO("Lesotho"),
    LETTONIE("Lettonie"),
    LIBAN("Liban"),
    LIBERIA("Liberia"),
    LIBYE("Libye"),
    LIECHTENSTEIN("Liechtenstein"),
    LITUANIE("Lituanie"),
    LUXEMBOURG("Luxembourg"),
    MACEDOINE_DU_NORD("Macédoine du Nord"),
    MADAGASCAR("Madagascar"),
    MALAISIE("Malaisie"),
    MALAWI("Malawi"),
    MALDIVES("Maldives"),
    MALI("Mali"),
    MALTE("Malte"),
    MAROC("Maroc"),
    MARSHALL("Îles Marshall"),
    MAURICE("Maurice") ,
    MAURITANIE("Mauritanie"),
    MEXIQUE("Mexique"),
    MICRONESIE("Micronésie"),
    MOLDAVIE("Moldavie"),
    MONACO("Monaco"),
    MONGOLIE("Mongolie"),
    MONTENEGRO("Monténégro"),
    MOZAMBIQUE("Mozambique"),
    MYANMAR("Myanmar"),
    NAMIBIE("Namibie"),
    NAURU("Nauru"),
    NEPAL("Népal"),
    NICARAGUA("Nicaragua"),
    NIGER("Niger"),
    NIGERIA("Nigeria"),
    NORVEGE("Norvège"),
    NOUVELLE_ZELANDE("Nouvelle-Zélande"),
    OMAN("Oman"),
    OUGANDA("Ouganda"),
    OUZBEKISTAN("Ouzbékistan"),
    PAKISTAN("Pakistan"),
    PALAOS("Palaos"),
    PALESTINE("Palestine"),
    PANAMA("Panama"),
    PAPOUASIE_NOUVELLE_GUINEE("Papouasie-Nouvelle-Guinée"),
    PARAGUAY("Paraguay"),
    PAYS_BAS("Pays-Bas"),
    PEROU("Pérou"),
    PHILIPPINES("Philippines"),
    POLOGNE("Pologne"),
    PORTUGAL("Portugal"),
    QATAR("Qatar"),
    REPUBLIQUE_DOMINICAINE("République dominicaine"),
    REPUBLIQUE_TCHEQUE("République tchèque"),
    ROUMANIE("Roumanie"),
    ROYAUME_UNI("Royaume-Uni"),
    RUSSIE("Russie"),
    RWANDA("Rwanda"),
    SAINT_KITTS_ET_NEVIS("Saint-Kitts-et-Nevis"),
    SAINTE_LUCIE("Sainte-Lucie"),
    SAINT_VINCENT_ET_LES_GRENADINES("Saint-Vincent-et-les-Grenadines"),
    SALOMON("Îles Salomon"),
    SAMOA("Samoa"),
    SAO_TOME_ET_PRINCIPE("Sao Tomé-et-Principe"),
    SENEGAL("Sénégal"),
    SERBIE("Serbie"),
    SEYCHELLES("Seychelles"),
    SIERRA_LEONE("Sierra Leone"),
    SINGAPOUR("Singapour"),
    SLOVAQUIE("Slovaquie"),
    SLOVENIE("Slovénie"),
    SOMALIE("Somalie"),
    SOUDAN("Soudan"),
    SOUDAN_DU_SUD("Soudan du Sud"),
    SRI_LANKA("Sri Lanka"),
    SUEDE("Suède"),
    SUISSE("Suisse"),
    SURINAME("Suriname"),
    SYRIE("Syrie"),

    SWAZILAND("Swaziland"), // Aussi connu sous le nom d'Eswatini
    TADJIKISTAN("Tadjikistan"),
    TAIWAN("Taïwan"),
    TANZANIE("Tanzanie"),
    TCHAD("Tchad"),
    THAILANDE("Thaïlande"),
    TIMOR_ORIENTAL("Timor oriental"),
    TOGO("Togo"),
    TONGA("Tonga"),
    TRINITE_ET_TOBAGO("Trinité-et-Tobago"),
    TUNISIE("Tunisie"),
    TURKMENISTAN("Turkménistan"),
    TURQUIE("Turquie"),
    TUVALU("Tuvalu"),
    UKRAINE("Ukraine"),
    URUGUAY("Uruguay"),
    VANUATU("Vanuatu"),
    VATICAN("Vatican"),
    VENEZUELA("Venezuela"),
    VIETNAM("Vietnam"),
    YEMEN("Yémen"),
    ZAMBIE("Zambie"),
    ZIMBABWE("Zimbabwe");
    private final String nom;

    Country(String nom) {
        this.nom = nom;
    }

    public String getNom() {
        return nom;
    }

    }
